apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: iam-main
spec:
  teamId: "iam"
  volume:
    size: 5Gi
  numberOfInstances: 2
  preparedDatabases:
    sbtest:
      defaultUsers: true
      schemas:
        sbtest:
          defaultRoles: false
          defaultUsers: false
  postgresql:
    version: "12"
    parameters:
      password_encryption: "scram-sha-256"
  patroni:
    pg_hba:
    # TYPE      DATABASE    USER      ADDRESS      METHOD
    - local     all         all                    trust
    - host      all         all       127.0.0.1/32 scram-sha-256
    - host      all         all       ::1/128      scram-sha-256
    - hostssl   replication standby   all          scram-sha-256
    - hostnossl replication all       all          reject
    - hostnossl sbtest      all       all          scram-sha-256
    - hostnossl all         all       all          reject
    - hostssl   all         all       all          scram-sha-256
  sidecars:
  - name: "exporter"
    image: "quay.io/prometheuscommunity/postgres-exporter:v0.9.0"
    ports:
    - name: exporter
      containerPort: 9187
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 256M
      requests:
        cpu: 50m
        memory: 100M
    env:
    - name: "DATA_SOURCE_URI"
      value: "localhost:5432/?sslmode=disable"
    - name: "DATA_SOURCE_USER"
      valueFrom:
        secretKeyRef:
          name: postgres.iam-main.credentials.postgresql.acid.zalan.do
          key: username
    - name: "DATA_SOURCE_PASS"
      valueFrom:
        secretKeyRef:
          name: postgres.iam-main.credentials.postgresql.acid.zalan.do
          key: password
    - name: "PG_EXPORTER_EXTEND_QUERY_PATH"
      value: "/etc/pg-exporter/queries.yaml"
    - name: "PG_EXPORTER_AUTO_DISCOVER_DATABASES"
      value: "true"
  additionalVolumes:
  - name: extra-queries
    targetContainers:
    - exporter
    mountPath: /etc/pg-exporter/queries.yaml
    subPath: queries.yaml
    volumeSource:
      configMap:
        name: extra-queries
---

apiVersion: v1
kind: Service
metadata:
  name: pg-exporter
  labels:
    app: pg-exporter
spec:
  ports:
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    cluster-name: iam-main
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: pg-exporter
  name: pg-exporter
spec:
  endpoints:
  - path: /metrics
    port: exporter
    relabelings:
    - replacement: service_cluster
      targetLabel: cluster
  selector:
    matchLabels:
      app: pg-exporter
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-queries
data:
  queries.yaml: |
    pg_postmaster:
      query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
      master: true
      metrics:
        - start_time_seconds:
            usage: "GAUGE"
            description: "Time at which postmaster started"
    
    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
      master: true
      cache_seconds: 30
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size_bytes:
            usage: "GAUGE"
            description: "Disk space used by the database"
